services:
  console-bot:
    container_name: console-bot
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_PASSWORD=${DB_PASSWORD}
      - BOT_TOKEN=${BOT_TOKEN}
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres
    container_name: ${DB_HOST}
    restart: unless-stopped
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
    expose:
      - ${DB_PORT}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "$$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
